### ISSUE TITLE
Settings don't work

### ISSUE THREAD

**Issue by JUNUX1** [AlexW00/StartTreeV2#8] opened 2022-02-03 05:11 UTC
I generated a start tree, and it's working nice. However, when I click on the settings icon in the up right corner, it just loads an empty page. I have this problem on brave browser version 1.33.106, I tried same on Firefox, everything was perfect, and I could use settings as you planned. Let me add I turned off brave-shield (that block ads, third party, ...) but the issue remain. Still, I don't know if the difficulty is general for chromium or not.

![Screenshot from 2022-02-03 08-37-00](https://user-images.githubusercontent.com/88236319/152284595-0e44be7c-f5dc-4c11-8e84-2834f277124a.png)

**Comment by AlexW00** [comment] 2022-02-03 06:40
> I generated a start tree, and it's working nice. However, when I click on the settings icon in the up right corner, it just loads an empty page. I have this problem on brave browser version 1.33.106, I tried same on Firefox, everything was perfect, and I could use settings as you planned. Let me add I turned off brave-shield (that block ads, third party, ...) but the issue remain. Still, I don't know if the difficulty is general for chromium or not.
> 
> 
> 
> ![Screenshot from 2022-02-03 08-37-00](https://user-images.githubusercontent.com/88236319/152284595-0e44be7c-f5dc-4c11-8e84-2834f277124a.png)
> 
> 

Thank you for the report, I will look into it!

**Comment by AlexW00** [comment] 2022-02-03 07:14
I just tested StartTree with the latest version of Brave, everything works fine.
Can you please show me the output of the browser console when loading the settings page?
You can open the console by pressing `Command+Option+J` on Mac or `Control+Shift+J` on Windows/Linux/ChromeOS

**Comment by JUNUX1** [comment] 2022-02-03 07:41
this is it:

![Screenshot from 2022-02-03 11-06-58](https://user-images.githubusercontent.com/88236319/152300779-7c3b07eb-3229-49dd-8b1a-13882d82559c.png)

**Comment by AlexW00** [comment] 2022-02-03 10:28
> this is it:
> 
> ![Screenshot from 2022-02-03 11-06-58](https://user-images.githubusercontent.com/88236319/152300779-7c3b07eb-3229-49dd-8b1a-13882d82559c.png)
Can you try disabling other add-ons/upgrading to a newer version and see if that fixes the issue?

**Comment by JUNUX1** [comment] 2022-02-04 06:45
> > this is it:
> > ![Screenshot from 2022-02-03 11-06-58](https://user-images.githubusercontent.com/88236319/152300779-7c3b07eb-3229-49dd-8b1a-13882d82559c.png)
> > Can you try disabling other add-ons/upgrading to a newer version and see if that fixes the issue?

I updated to the latest version, still remains.
The interesting part is I installed the latest stable version of Google Chrome and the same problem, let me repeat it's nice and working on Firefox.
However, I tried opening settings on another machine, Google Chrome, Microsoft Edge and everything was just fine!
So the issue is somehow related to my laptop and not to your project.
Should I close the issue?

**Comment by AlexW00** [comment] 2022-02-04 07:36
> > > this is it:
> 
> > > ![Screenshot from 2022-02-03 11-06-58](https://user-images.githubusercontent.com/88236319/152300779-7c3b07eb-3229-49dd-8b1a-13882d82559c.png)
> 
> > > Can you try disabling other add-ons/upgrading to a newer version and see if that fixes the issue?
> 
> 
> 
> I updated to the latest version, still remains.
> 
> The interesting part is I installed the latest stable version of Google Chrome and the same problem, let me repeat it's nice and working on Firefox.
> 
> However, I tried opening settings on another machine, Google Chrome, Microsoft Edge and everything was just fine!
> 
> So the issue is somehow related to my laptop and not to your project.
> 
> Should I close the issue?

That's a really weird bug... I'm closing the issue now, but I'd love to hear an update on it if you ever find out what has been the cause of it.

**Closed** 2022-02-04 07:36 UTC
